swagger: "2.0"
info:
  title: "代码大数据平台API文档"
  version: "1.0.0"
host: "10.141.221.85:5001"
basePath: "/"

schemes:
- "http"

paths:
  /totalbasic:
    get:
      tags:
      - "basic_info"
      operationId: "getTotalBasic"
      summary: "repo基础信息查询接口"
      description: "该函数用来获取总共爬取了多少repo的基础信息"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: OK
          schema:
            type: "string"
            example: "123456"
        500:
          description: "查询失败或异常"  


  /totalclone:
    get:
      tags:
      - "cloned_repo"
      operationId: "getTotalClone"
      summary: "已经clone下的repo查询接口"
      description: "该函数用来获取总共服务器上有多少repo"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: OK
          schema:
            type: "string"
            example: "123456"
        500:
          description: "查询失败或异常"  


  /repobasicinfo/{days}/:
    get:
      tags:
      - "basic_info"
      operationId: "show_basicInfo"
      summary: "repo基本信息的增量"
      description: "该函数基本信息新增的数量(一日内，七日内，一月内)"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "days"
          in: "path"
          type: "string"
          description: "repo基础信息"
          required: true
      responses:
        200:
          description: OK
          schema:
            type: "string"
            example : "123456"
        500:
          description: "查询失败或异常" 

  /repoclone/{days}/:
    get:
      tags:
      - "cloned_repo"
      operationId: "get_repoClone"
      summary: "repo的clone的增量"
      description: "该函数用来获取项目clone的情况（一日内，七日内，一月内）"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: "days"
        in: "path"
        type: "string"
        description: "repo的clone信息"
        required: true
      responses:
        200:
          description: OK
          schema:
            type: "string"
            example : "123456"
        500:
          description: "查询失败或异常" 


  /repocloneinfo/{pages}/:
    get:
      tags:
      - "cloned_repo，basic_info"
      operationId: "getRepoCloneInfo"
      summary: "repo的clone的增量的基本信息"
      description: "该函数用来得到已经clone的repo的基本信息情况"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: "pages"
        in: "path"
        type: "string"
        description: "repo的clone基本信息,省略参数则默认为第一页"
        required: true
      responses:
        200:
          description: OK
          schema: 
            type: "array"
            items:
                $ref: "#/definitions/repoinfo"

        500:
          description: "查询失败或异常" 
          

definitions: 
  repoinfo:
    type: object
    properties:
      git_address: 
        type: string
      owner_name: 
        type: string
      pushed_at:
        type: string
        format: date-time
      repos_name: 
        type: string
      scan_time:
        type: string
        format: date-time
      
  


